# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:title/

# Setup
title:            EdSurge Careers
tagline:          Become an EdSurgent
description:      Open Positions at EdSurge
url:              http://careers.edsurge.com

author:
  name:           'EdSurge'
  url:            https://twitter.com/edsurge

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/edsurge/careers.edsurge.com
